apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - app
{% if db %}
  - db
{% endif %}

commonLabels:
  app.kubernetes.io/part-of: {{ project_name }}

{% if db %}
secretGenerator:
  - name: {{ project_name }}-secrets
    literals:
      - POSTGRES_USER={{ project_name }}
      - POSTGRES_PASSWORD={{ project_name }}
{% endif %}
