[tool.poetry]
name = "srec_nlp"
version = "0.2.1"
description = ""
authors = ["Stelios Tymvios <stelios.tymvios@icloud.com>"]

[tool.poetry.dependencies]
python = "^3.6"
google-cloud = "^0.34.0"
scipy = "^1.3"
numpy = "^1.16"
sklearn = "^0.0.0"
ibm-watson = "^3.0"
google-cloud-language = "^1.2"
paralleldots = "^3.2"
aylien-apiclient = "^0.7.0"
attrs = "^19.1"
Cython = "^0.29.9"
pybind11 = "^2.2"

[tool.poetry.dev-dependencies]
black = {version = "^18.3-alpha.0",allows-prereleases = true}
pytest = "^4.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
